# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-11 13:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBikes',
            fields=[
                ('stand_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='number')),
                ('stand_name', models.CharField(max_length=80, verbose_name='name')),
                ('position', django.contrib.gis.db.models.fields.PointField(max_length=100, srid=4326, verbose_name='position')),
                ('total_bike_stands', models.IntegerField(verbose_name='bike_stands')),
                ('available_bike_stands', models.IntegerField(verbose_name='available_bike_stands')),
                ('available_bikes', models.IntegerField(verbose_name='available_bikes')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True, verbose_name='email')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='last known location')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dublinbikes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='user_id'),
        ),
    ]
