# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 19:31
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170412_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinbikes',
            name='last_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dublinbikes',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(default=datetime.datetime(2017, 4, 19, 19, 31, 39, 427358, tzinfo=utc), srid=6432, verbose_name='position'),
            preserve_default=False,
        ),
    ]
