# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170419_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinbikes',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
